### ISSUE TITLE
RetroArch not download

### ISSUE THREAD

**Issue by RaptorPharaoh** [Slashbunny/gog-galaxy-plugin-downloader#15]
Hello, please can you say me what's the code to download the RetroArch Plugin? I tested every name but the updater crashed every time. This is my actual bat config, I think I have all plugins  excepting RetroArch [https://github.com/jshackles/RetroGOG]

gog-plugins-downloader.exe -p battlenet,twitch,discord,itch,wargaming,ffxiv,gw2,minecraft,3ds,n64,nds,nes,ngameboy,ncube,nwii,nwiiu,snes,psp,ps2,uplay,steam,rockstar,psn,paradox,origin,epic,bethesda,vision,test,humble,pathofexile,nswitch

Thanks :)

**Comment by Slashbunny** [comment]
Greetings!

Currently, the released version of that plugin only includes the N64 plugin. That's what this tool is downloading and installing right now: [Release 0.2](https://github.com/jshackles/RetroGOG/releases) that only includes N64. 

There are also some problems with supporting the https://github.com/jshackles/RetroGOG project, even if a new version were released with all the plugins:

1. The project is not 1 plugin. It's 19 plugins in a single git repository. **gog-galaxy-plugin-downloader** assumes that there is 1 plugin to 1 download. I will have to add support to say "This download includes 19 plugins" in the configuration. In addition, this will make updating and version checking very complicated. There is no concept of "groups" of plugins that are all in a single download with an associated version number, separate from the individual plugin version number.
2. The project reuses existing GOG Galaxy plugin names, like `3ds`, `n64`, `snes`, `nes`, `ps1`, etc. You can't have jshackles `snes` plugin installed at the same time as the https://github.com/AHCoder/galaxy-integration-snes `snes` plugin, for example, because they are using the same name. So which plugin should we choose? The older one or the newer RetroArch one? This tool supports specifying a different plugins yaml file, so maybe something like `gog-plugins-downloader.exe -c retroarch-plugins.yml` could be done to keep the plugins separate, but I will still need to solve the first problem.

I think since all 19 plugins are all in a single git repository, it is probably easiest to follow jshackles' instructions and simply download everything as a `zip` file and manually extract into your plugins directory, per the README: https://github.com/jshackles/RetroGOG#tutorial

**Comment by RaptorPharaoh** [comment]
Hi, oh ok, I thought it was a normal plugin like the ps2, thanks for explain me how it works :) and thanks for attend my comment :)  Have a good day.

**Comment by Slashbunny** [comment]
I am going to close this issue since it would be too much effort to add support for multiple-plugins-in-a-single-project type of setup.
