### ISSUE TITLE
[Request/Question] Skip "Process Complete"

### ISSUE THREAD

**Issue by SonOfDiablo** [Slashbunny/gog-galaxy-plugin-downloader#20]
Is there a way to skip "Process complete! Press the Enter key to exit..."?

I have a bulk command that updates a number of things and it's quite annoying having to remember to hit enter when it's done updating GOG Galaxy plugins.

**Comment by Slashbunny** [comment]
@SonOfDiablo Yes, I will just remove that entirely. I added it for Windows users who might just double click on the `.exe` file and have the console briefly pop up and go away without having a chance to view the output. But that is easily fixed by having the user create a custom `.bat` instead. 

I already committed the change, but I need to rebuild the `.exe` and create a new release.

**Comment by Slashbunny** [comment]
@SonOfDiablo Release v0.2.3 has the prompt removed:

https://github.com/Slashbunny/gog-galaxy-plugin-downloader/releases/tag/v0.2.3
